apiVersion: v1
kind: Template
labels:
  template: appointment-frontend
metadata:
  name: appointment-frontend
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: "${NAME}"
      labels:
        app: "${NAME}"
    spec:
      ports:
        - name: web
          port: 2015
          targetPort: 2015
      selector:
        app: "${NAME}"
  - apiVersion: v1
    kind: Route
    metadata:
      name: "${NAME}"
    spec:
      host: "${APPLICATION_DOMAIN}"
      to:
        kind: Service
        name: "${NAME}"
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      annotations:
        description: "Defines how to deploy the application server"
      name: "${NAME}"
    spec:
      replicas: 2
      selector:
        name: ${NAME}
      strategy:
        type: Rolling
        rollingParams:
          updatePeriodSeconds: 1
          intervalSeconds: 1
          timeoutSeconds: 60
          maxSurge: 2
          maxUnavailable: 1
        resources: {}
        activeDeadlineSeconds: 3600
      template:
        metadata:
          labels:
            app: "${NAME}"
            name: "${NAME}"
        spec:
          containers:
            - name: "${NAME}"
              image: " "
              args:
                - "/tmp/scripts/run"
              ports:
                - containerPort: 2015
              readinessProbe:
                failureThreshold: 3
                initialDelaySeconds: 3
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 2015
                timeoutSeconds: 3
              livenessProbe:
                failureThreshold: 3
                initialDelaySeconds: 3
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 2015
                timeoutSeconds: 3
              volumeMounts:
                - mountPath: /var/www/html/static/keycloak
                  name: keycloak
              terminationMessagePath: "/dev/termination-log"
              terminationMessagePolicy: File
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: 50m
                  memory: 256Mi
                limits:
                  cpu: 100m
                  memory: 512Mi
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
          volumes:
            - configMap:
                defaultMode: 420
                name: keycloak.json
              name: keycloak
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: name
                        operator: In
                        values:
                          - "${NAME}"
                  topologyKey: kubernetes.io/hostname
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - "${NAME}"
            from:
              kind: ImageStreamTag
              namespace: ${TOOLS_WORKSPACE}
              name: "${NAME}:${IMAGE_TAG}"
parameters:
  - name: NAME
    displayName: Name
    description: The suffix for all created objects
    required: false
    value: appointment-frontend
  - name: APPLICATION_DOMAIN
    description: "The exposed hostname that will route to the Vue application"
    value: dev-bookanappointment.pathfinder.gov.bc.ca
  - name: IMAGE_TAG
    description: The image tag to pull for the deployment.
    required: true
    value: latest
  - name: TOOLS_WORKSPACE
    description: The Location for your image streams (Tools Workspace)
    required: true
    value: servicebc-cfms-tools
