---
kind: Template
apiVersion: v1
metadata:
  name: "queue-management"
parameters:
- name: BASE_IMAGE_NAME
  displayName: BASE_IMAGE_NAME
  description: The caddy image to build the Vue app from
  required: true
  value: servicebc-cfms-caddy-npm-56
objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    annotations:
      description: Defines how to build the application
      template.alpha.openshift.io/wait-for-ready: 'true'
    labels:
      app: queue-management
    name: "${BASE_IMAGE_NAME}"
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: "${BASE_IMAGE_NAME}:latest"
    runPolicy: Serial
    source:
      dockerfile: >-
        FROM openshift/bcgov-s2i-caddy:latest

        USER root

        RUN yum install -y gcc-c++ make && curl -sL https://rpm.nodesource.com/setup_8.x | bash - && yum install -y nodejs && npm -v

        USER 1001
      type: Dockerfile
    strategy:
      dockerStrategy: {}
      type: Docker
    triggers: []
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${BASE_IMAGE_NAME}"
    annotations:
      description: "Base image for performing httpd builds"
