---
kind: Template
apiVersion: v1
metadata:
  name: queue-management-frontend
parameters:
- name: NAME
  displayName: Name
  description: The suffix for all created objects
  required: false
  value: queue-management-frontend
- name: GIT_REPO
  displayName: GIT_REPO
  description: URL to GitHub repo with static content
  required: true
  value: https://github.com/sjrumsby/queue-management.git
- name: GIT_REF
  displayName: GIT_REF
  description: Branch related to GitHub repo
  required: true
  value: proof-of-concept
- name: SOURCE_IMAGE
  displayName: SOURCE_IMAGE
  description: Source image name
  required: true
  value: bcgov-s2i-caddy
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${NAME}"
    creationTimestamp: 
    labels:
      app: "${NAME}"
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ''
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${NAME}"
    creationTimestamp: 
    labels:
      app: "${NAME}"
  spec:
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
    runPolicy: SerialLatestOnly
    source:
      type: Git
      contextDir: "/frontend"
      git:
        uri: "${GIT_REPO}"
        ref: "${GIT_REF}"
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          namespace: openshift
          name: "${SOURCE_IMAGE}:latest"
    output:
      to:
        kind: ImageStreamTag
        name: "${NAME}:latest"
    resources: {}
    postCommit: {}
    nodeSelector: 
    successfulBuildsHistoryLimit: 5
    failedBuildsHistoryLimit: 5
