---
kind: Template
apiVersion: v1
metadata:
  name: "queue-management-frontend"
parameters:
- name: NAME
  displayName: Name
  description: The suffix for all created objects
  required: false
  value: queue-management-frontend
- name: APPLICATION_DOMAIN
  description: "The exposed hostname that will route to the Vue application"
  value: "servicebc-cfms-dev.pathfinder.gov.bc.ca"
- name: IMAGE_TAG
  description: The image tag to pull for the deployment.
  required: true
  value: dev
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: "${NAME}"
    creationTimestamp: 
    labels:
      app: "${NAME}"
  spec:
    ports:
    - name: web
      protocol: TCP
      port: 2015
      targetPort: 2015
    selector:
      app: "${NAME}"
    type: ClusterIP
    sessionAffinity: None
- kind: Route
  apiVersion: v1
  metadata:
    name: "${NAME}"
  spec:
    host: "${APPLICATION_DOMAIN}"
    to:
      kind: Service
      name: "${NAME}"
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${NAME}"
    creationTimestamp: 
    labels:
      app: queue-management
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 60
        maxUnavailable: 1
      resources: {}
      activeDeadlineSeconds: 21600
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${NAME}"
        from:
          kind: ImageStreamTag
          namespace: servicebc-cfms-tools
          name: "${NAME}:${IMAGE_TAG}"
    replicas: 3
    revisionHistoryLimit: 10
    test: false
    selector:
      app: "${NAME}"
      deploymentconfig: "${NAME}"
    template:
      metadata:
        creationTimestamp: 
        labels:
          app: "${NAME}"
          deploymentconfig: "${NAME}"
      spec:
        containers:
        - name: "${NAME}"
          image: " "
          args:
            -  "/tmp/scripts/run"
          ports:
          - containerPort: 2015
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 2015
            timeoutSeconds: 3
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 2015
            timeoutSeconds: 3
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
          volumeMounts:
            - mountPath: /var/www/html/static/videos
              name: frontend-videos
              readOnly: false
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: "frontend-videos"
  spec:
    accessModes: [ "ReadWriteMany" ]
    resources:
      requests:
        storage: "1Gi"