---
kind: Template
apiVersion: v1
metadata:
  name: "queue-management"
parameters:
- name: BASE_IMAGE_NAME
  displayName: BASE_IMAGE_NAME
  description: The base httpd image to start from
  required: true
  value: httpd-24-centos7-npm-56
- name: FRONTEND_IMAGE_NAME
  displayName: FRONTEND_IMAGE_NAME
  description: The image of the resulting built Vue app
  required: true
  value: queue-management-frontend
- name: BASE_API_URL
  displayName: BASE_API_URL
  description: The URL of the queue-management api
  required: true
  value: "https://api-servicebc-cfms-dev.pathfinder.gov.bc.ca/"
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${BASE_IMAGE_NAME}"
    annotations:
      description: "Base image for performing httpd builds"
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${FRONTEND_IMAGE_NAME}"
    annotations:
      description: "Keeps track of changes in the application image"
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${BASE_IMAGE_NAME}"
    annotations:
      description: "Defines how to build the application"
      template.alpha.openshift.io/wait-for-ready: "true"
  spec:
    source:
      dockerfile: >-
        FROM centos/httpd-24-centos7

        USER root

        RUN yum install -y gcc-c++ make && curl -sL https://rpm.nodesource.com/setup_8.x | bash - && yum install -y nodejs && npm -v

        USER 1001
      type: Dockerfile
    strategy:
      type: Docker
    output: 
      to: 
        kind: ImageStreamTag
        name: "${BASE_IMAGE_NAME}:latest"
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "queue-management-frontend"
    annotations:
      description: "Defines how to build the application"
      template.alpha.openshift.io/wait-for-ready: "true"
  spec:
    source:
      type: Git
      git:
        uri: https://github.com/sjrumsby/queue-management.git
        ref: proof-of-concept
      contextDir: "/frontend"
    strategy:
      type: Source
      sourceStrategy:
        env:
        - name: BASE_API_URL
          value: "${BASE_API_URL}"
        from:
          kind: ImageStreamTag
          name: "httpd-24-centos7-npm-56:latest"
    output:
      to:
        kind: ImageStreamTag
        name: "${FRONTEND_IMAGE_NAME}:latest"
